_wandb:
    value:
        cli_version: 0.22.3
        e:
            etcn89pjqclic7lk323wabthfk7xnqkm:
                codePath: current_models/lowrank_model_v2.py
                codePathLocal: lowrank_model_v2.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "765889540096"
                        used: "18004041728"
                email: hyewona@mit.edu
                executable: /orcd/home/002/hyewona/lr-act/lora/bin/python3
                git:
                    commit: a019a8887ec0be34d5d558d5fcc5332b040f8e38
                    remote: git@github.mit.edu:hyewona/lr_activations.git
                gpu: NVIDIA L40S
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-b5f75602-f690-3f1f-b33e-51420f1aa135
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-2b5bfb95-6bda-4632-2dbb-5a1ec7c926cc
                host: node3005
                memory:
                    total: "1081411747840"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /orcd/home/002/hyewona/lr-act/current_models/lowrank_model_v2.py
                python: CPython 3.13.5
                root: /orcd/home/002/hyewona/lr-act/current_models
                slurm:
                    cluster_name: eofe7
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: mit_general
                    job_cpus_per_node: "4"
                    job_end_time: "1765487813"
                    job_gid: "100208845"
                    job_gpus: 2,3
                    job_id: "7119339"
                    job_name: interactive
                    job_nodelist: node3005
                    job_num_nodes: "1"
                    job_partition: mit_normal_gpu
                    job_qos: normal
                    job_start_time: "1765486013"
                    job_uid: "208845"
                    job_user: hyewona
                    jobid: "7119339"
                    launch_node_ipaddr: 10.1.221.1
                    localid: "0"
                    mem_per_node: "12288"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: node3005
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "38301"
                    pty_win_col: "191"
                    pty_win_row: "27"
                    script_context: prolog_task
                    srun_comm_host: 10.1.221.1
                    srun_comm_port: "41483"
                    step_id: "4294967290"
                    step_launcher_port: "41483"
                    step_nodelist: node3005
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /orcd/home/002/hyewona/lr-act
                    submit_host: orcd-login001.mit.edu
                    task_pid: "328620"
                    tasks_per_node: "1"
                    topology_addr: node3005
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2025-12-11T20:47:42.454805Z"
                writerId: etcn89pjqclic7lk323wabthfk7xnqkm
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "4": 3.13.5
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
